# Generated by Django 5.1.2 on 2024-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
