# Generated by Django 5.1.2 on 2024-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_rename_variation_category_variation_category_and_more"),
        ("cart", "0003_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="Product.variation"),
        ),
    ]
